In [1]:
import numpy as np

In [128]:
###
# X = [[x01,x02,...,x0d], [xN1,xN2,...,xNd]]
# y = [y0,y1,y2,...,yN]
# X_new = [x01, x02,...,x0d]
###


class KNN:
    def __init__(self, k = 3):
        self.X = None
        self.y = None
        self.k = k

    def fit(self,X, y):
        self.X = X
        self.y = y

    def predict(self, X_new, method = 'cos'):
        dist = self.distance(X_new, self.X, method) #(N,M)
        index = np.argsort(dist, axis = 0)[:self.k,:] #(K,M)
        result = np.mean(self.y[index], axis = 0) #(M,)
        return result

    def distance(self, X_new, X, method = 'cos'):
        if method == 'cos':
            X_norm = np.sqrt(np.sum(X**2, axis = 1)) #(N,)
            X_new_norm = np.sqrt(np.sum(X_new**2, axis = 1)) #(M,)
            dot_prod = X @ X_new.T #(N,M)
            norm = X_norm[:,np.newaxis] * X_new_norm[np.newaxis,:] #(N,M)
            dist = 1-dot_prod/norm #(N,M)
        elif method == 'euclid':
            dist = np.sqrt(np.sum((X[:,np.newaxis,:] - X_new[np.newaxis,:])**2, axis = 2)) #(N,M)
        return dist


In [ ]:
#X (N,p)
#X_new (M,p)
#dist (M,N,p)

# X (N,1,p)
# X_new (1,M,p)
# X - X_new (N,M,p)

# np.sum((X-X_new)**2, axis = 2) (N,M)
#distance want (M,k)

In [121]:
def distance(X_new, X, method = 'cos'):
    if method == 'cos':
        X_norm = np.sqrt(np.sum(X**2, axis = 1)) #(N,)
        X_new_norm = np.sqrt(np.sum(X_new**2, axis = 1)) #(M,)

        dot_prod = X @ X_new.T #(N,M)
        norm = X_norm[:,np.newaxis] * X_new_norm[np.newaxis,:] #(N,M)
        dist = 1-dot_prod/norm #(N,M)
    elif method == 'euclid':
        dist = np.sqrt(np.sum((X[:,np.newaxis,:] - X_new[np.newaxis,:])**2, axis = 2)) #(N,M)
    return dist

In [117]:
X = np.array([[1,2,3],[2,3,4],[3,4,5]]) #(N,p)
X_new = np.array([[1,2,3],[2,3,4]]) #(M,p)


In [124]:
dist = distance(X_new,X,'cos')

In [127]:
np.argsort(dist)[:2,:]

array([[0, 1],
       [1, 0]])

In [123]:
distance(X_new,X,'euclid')

array([[0.        , 1.73205081],
       [1.73205081, 0.        ],
       [3.46410162, 1.73205081]])

In [110]:
# calculate cosine similarity

# cos(x,y) = xy/(|x||y|)

x = np.array([[1,2,3],[2,3,4],[3,4,5]]) #(N,p)
y = np.array([[1,2,3],[2,3,4]]) #(M,p)

x_norm = np.sqrt(np.sum(x**2, axis = 1)) #(N,)
y_norm = np.sqrt(np.sum(y**2, axis = 1)) #(M,)

dot_prod = x @ y.T #(N,M)
norm = x_norm[:,np.newaxis] * y_norm[np.newaxis,:] #(N,M)
dist = dot_prod/norm #(N,M)


In [111]:
dist

array([[1.        , 0.99258333],
       [0.99258333, 1.        ],
       [0.98270763, 0.99792889]])

In [108]:
x_norm * y_norm[:,np.newaxis] #(M,N)

array([[14.        , 20.14944168, 26.45751311],
       [20.14944168, 29.        , 38.07886553]])

In [100]:
np.argsort(dist, axis = 1)[:,:2]

array([[0, 1],
       [2, 0]])

In [79]:
y = np.array([1,2,1])
y.shape

(3,)

In [84]:
X = np.array([[2,2,2],[1,1,1], [3,3,3]])

array([[1, 2, 1]])

In [73]:
X = np.array([[2,2,2],[1,1,1], [3,3,3]])
y = np.array([1,2,1])

knn = KNN(2)
knn.fit(X,y)

In [77]:
X_new = np.array([[1,2,1], [2,8,2]])
knn.predict(X_new, method = 'euclid')

[[1.41421356 6.        ]
 [1.         7.14142843]
 [3.         5.19615242]]
[[1 2]
 [0 0]]


array([1.5, 1. ])