In [1]:
import numpy as np

In [7]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3 4]]


In [4]:
# check shape
print(x.shape)
print(y.shape)

(3, 3)
(1, 3)


## Vector addition and substraction

In [5]:
# broadcast in addition and substraction
x-y

array([[-1, -1, -1],
       [ 2,  2,  2],
       [ 5,  5,  5]])

In [15]:
# broadcast when shape does not compatible
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
z = np.array([[2,3,4],[3,4,5]])
print(x)
print(z)
print(x.shape)
print(z.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3 4]
 [3 4 5]]
(3, 3)
(2, 3)


In [16]:
# want to get (3,2,3)
# expand x: (3,1,3)
# expand z: (1,2,3)
x[:,np.newaxis,:] - z[np.newaxis,:]

array([[[-1, -1, -1],
        [-2, -2, -2]],

       [[ 2,  2,  2],
        [ 1,  1,  1]],

       [[ 5,  5,  5],
        [ 4,  4,  4]]])

## Vector/Matrix multiplication

In [17]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[2,3,4]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3 4]]


In [22]:
# matrix multiplication A(m*n) B(n*m) -> AB(m*m) BA(n*n)
A = np.array([[1,2],[4,5],[7,8]])
B = np.array([[1,2,3],[2,3,4]])
print(A@B)
print(B@A)

[[ 5  8 11]
 [14 23 32]
 [23 38 53]]
[[30 36]
 [42 51]]
